# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_level',
            new_name='zipcode',
        ),
    ]
