# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20171010_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
