# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_auto_20171010_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='quantity',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
