# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_trade_quantity'),
        ('users', '0004_auto_20171010_1307'),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('review', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.User')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critiques', to='users.User')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trades.Trade')),
            ],
        ),
    ]
